apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-github-stats-crawler
spec:
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: GitHub issues crawler.
      name: GitHub Stats Crawler
    spec:
      repository: elastic/issue-crawler
      teams:
        ci-systems: {}
  owner: group:ci-systems
  type: buildkite-pipeline
