# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-github-stats-crawler
spec:
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: GitHub issues crawler.
      name: GitHub Stats Crawler
    spec:
      repository: elastic/issue-crawler
      teams:
        ci-systems: {}
  owner: group:productivity-foundations
  type: buildkite-pipeline
