agents:
  useVault: true
  image: "docker.elastic.co/employees/nkammah/github-stats-crawler:1.7"

steps:

  - label: ":wave: Greetings"
    command: "/issue-crawler-buildkite-pipeline/crawl.sh"
    env:
      PRIVATE_REPOS: "elastic/ci"
    plugins:
      - thedyrt/skip-checkout#v0.1.1: ~