agents:
  useVault: true
  image: "docker.elastic.co/employees/nkammah/github-stats-crawler:1.2"

steps:
  - plugins:
    # The GH repo is not needed since the github-issue crawler code is contained within the issue-crawler image
    - thedyrt/skip-checkout#v0.1.1: ~
  - label: ":wave: Greetings"
    command: "crawl.sh"
    env:
      PRIVATE_REPOS: "elastic/ci"