agents:
  useVault: true
  image: "docker.elastic.co/ci-agent-images/ci-systems/github-stats-crawler:1.0"

steps:
  - label: ":wave: Greetings"
    command: "crawl.sh"
    env:
      PRIVATE_REPOS: "elastic/ci"